default: &default
  adapter: postgresql
  username: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cycle_count

test:
  <<: *default
  database: cycle_count_test

production:
  <<: *default
  database: cycle_count
